version: '2'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
     - ./backend:/backend

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/src
    environment:
      - NODE_ENV=dev
    # Before you run this file for the first time, make sure 
    # you remove node_modules/ folders in your host machine
    command: >
      sh -c '
      echo "installing node modules in container";
      if test -d node_modules;
      then
        echo node_modules_exists ;
      else
        cp -a /tmp/node_modules /src;
      fi && 
      npm install &&
      node server.js
      '

  worker:
    build:
      context: ./celery
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./celery:/celery

  monitor:
    build:
      context: ./celery
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    entrypoint: flower
    command: -A tasks --port=5555 --broker=redis://redis:6379/0 
    depends_on:
       - redis
    volumes:
       - ./celery:/celery
  redis:
    image: redis
    env_file:
      - .env
